'use strict';

// Schmale, benannte API für den Renderer. Kein Zugriff auf ipcRenderer, Node oder den Token.
const { contextBridge, ipcRenderer } = require('electron');

const EVENT_TYPES = new Set([
  'status',
  'message:create',
  'message:update',
  'message:delete',
  'typing',
  'guilds:changed',
  'channels:changed',
  'dms:changed',
  'ai:changed',
  'ai:replied',
  'ai:busy',
  'presence',
  'user:renamed',
  'blocklist',
  'remote:activity',
  'remote:pending',
  'help:status',
  'help:pending',
  'help:activity',
  'ai:job-done',
  'lock',
  'ratelimit',
  'log',
  'update',
  'voice:state',
  'voice:speaking',
  'voice:members',
  'threads:changed',
  'interaction',
]);

const call = (channel) => (payload) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld('api', {
  getStatus: call('pk:get-status'),
  getAppInfo: call('pk:get-app-info'),
  checkForUpdates: call('pk:check-updates'),
  installUpdate: call('pk:install-update'),
  connect: call('pk:connect'),
  openEnvFile: call('pk:open-env-file'),
  getInviteUrl: call('pk:get-invite-url'),
  listGuilds: call('pk:list-guilds'),
  listChannels: call('pk:list-channels'),
  getPreviews: call('pk:get-previews'),
  getMessages: call('pk:get-messages'),
  sendMessage: call('pk:send-message'),
  sendTyping: call('pk:send-typing'),
  searchMentionables: call('pk:search-mentionables'),
  searchPeople: call('pk:search-people'),
  logError: call('pk:log-error'),
  errorReport: call('pk:error-report'),
  openLogFolder: call('pk:open-log-folder'),
  setupCheck: call('pk:setup-check'),
  blocklistGet: call('pk:blocklist-get'),
  remoteStatus: call('pk:remote-status'),
  helpStatus: call('pk:help-status'),
  helpRequest: call('pk:help-request'),
  helpStop: call('pk:help-stop'),
  helpControl: call('pk:help-control'),
  helpDecide: call('pk:help-decide'),
  helpDisconnect: call('pk:help-disconnect'),
  helpSetRelay: call('pk:help-set-relay'),
  remoteSetPassword: call('pk:remote-set-password'),
  remoteEnable: call('pk:remote-enable'),
  remoteOptions: call('pk:remote-options'),
  remotePair: call('pk:remote-pair'),
  remoteCancelPair: call('pk:remote-cancel-pair'),
  remoteDecide: call('pk:remote-decide'),
  remoteRemoveDevice: call('pk:remote-remove-device'),
  blocklistUpdate: call('pk:blocklist-update'),
  setPresence: call('pk:set-presence'),
  lockHello: call('pk:lock-hello'),
  lockSetHello: call('pk:lock-set-hello'),
  helloStatus: call('pk:hello-status'),
  backgroundGet: call('pk:background-get'),
  backgroundSet: call('pk:background-set'),
  updateChanges: call('pk:update-changes'),
  userProfile: call('pk:user-profile'),
  getSettings: call('pk:get-settings'),
  lockStatus: call('pk:lock-status'),
  lockVerify: call('pk:lock-verify'),
  lockSet: call('pk:lock-set'),
  lockIdle: call('pk:lock-idle'),
  lockClear: call('pk:lock-clear'),
  lockNow: call('pk:lock-now'),
  autostartGet: call('pk:autostart-get'),
  autostartSet: call('pk:autostart-set'),
  soundCustomInfo: call('pk:sound-custom-info'),
  soundCustomGet: call('pk:sound-custom-get'),
  soundCustomSet: call('pk:sound-custom-set'),
  soundCustomClear: call('pk:sound-custom-clear'),
  setScreenProtection: call('pk:set-screen-protection'),
  setReadMarker: call('pk:set-read-marker'),
  setLastLocation: call('pk:set-last-location'),
  openExternal: call('pk:open-external'),
  tokenInfo: call('pk:token-info'),
  tokenSave: call('pk:token-save'),
  tokenClear: call('pk:token-clear'),
  tokenShare: call('pk:token-share'),
  tokenImport: call('pk:token-import'),
  invitePreview: call('pk:invite-preview'),
  editMessage: call('pk:edit-message'),
  endPoll: call('pk:end-poll'),
  deleteMessage: call('pk:delete-message'),
  react: call('pk:react'),
  listPins: call('pk:list-pins'),
  setPinned: call('pk:set-pinned'),
  listThreads: call('pk:list-threads'),
  createThread: call('pk:create-thread'),
  getThread: call('pk:get-thread'),
  searchMessages: call('pk:search-messages'),
  listEmojis: call('pk:list-emojis'),
  commandsState: call('pk:commands-state'),
  getProfile: call('pk:get-profile'),
  listDMs: call('pk:list-dms'),
  channelRename: call('pk:channel-rename'),
  channelMove: call('pk:channel-move'),
  channelCreate: call('pk:channel-create'),
  memberInfo: call('pk:member-info'),
  memberRole: call('pk:member-role'),
  memberTimeout: call('pk:member-timeout'),
  memberKick: call('pk:member-kick'),
  memberBan: call('pk:member-ban'),
  copyText: call('pk:copy-text'),
  aiGet: call('pk:ai-get'),
  aiSetConfig: call('pk:ai-set-config'),
  aiSetKey: call('pk:ai-set-key'),
  aiClearKey: call('pk:ai-clear-key'),
  aiTest: call('pk:ai-test'),
  aiSaveJob: call('pk:ai-save-job'),
  aiDeleteJob: call('pk:ai-delete-job'),
  aiRunJob: call('pk:ai-run-job'),
  aiSetResponder: call('pk:ai-set-responder'),
  aiPreviewJob: call('pk:ai-preview-job'),
  aiSetLimits: call('pk:ai-set-limits'),
  aiSaveProfile: call('pk:ai-save-profile'),
  aiUseProfile: call('pk:ai-use-profile'),
  aiDeleteProfile: call('pk:ai-delete-profile'),
  aiAbort: call('pk:ai-abort'),
  aiModels: call('pk:ai-models'),
  aiFindLocal: call('pk:ai-find-local'),
  aiSetOptions: call('pk:ai-set-options'),
  aiConnect: call('pk:ai-connect'),
  aiMemoryList: call('pk:ai-memory-list'),
  aiMemoryView: call('pk:ai-memory-view'),
  aiMemoryForget: call('pk:ai-memory-forget'),
  aiMemoryForgetAll: call('pk:ai-memory-forget-all'),
  aiMemoryCompact: call('pk:ai-memory-compact'),
  aiMemorySetSummary: call('pk:ai-memory-set-summary'),
  setActiveChat: call('pk:set-active-chat'),
  openDM: call('pk:open-dm'),
  updateProfile: call('pk:update-profile'),
  refresh: call('pk:refresh'),
  channelAccess: call('pk:channel-access'),
  // Sprachkanäle
  listVoiceMembers: call('pk:list-voice-members'),
  voiceState: call('pk:voice-state'),
  voiceJoin: call('pk:voice-join'),
  voiceLeave: call('pk:voice-leave'),
  voiceTalk: call('pk:voice-talk'),
  voiceListen: call('pk:voice-listen'),
  voicePacket(data) {
    if (data instanceof Uint8Array && data.byteLength > 0 && data.byteLength <= 1500) ipcRenderer.send('pk:voice-packet', data);
  },
  onVoiceAudio(callback) {
    const listener = (_e, msg) => {
      if (msg && typeof msg.userId === 'string' && msg.data instanceof Uint8Array) callback(msg.userId, msg.data);
    };
    ipcRenderer.on('pk:voice-audio', listener);
    return () => ipcRenderer.removeListener('pk:voice-audio', listener);
  },
  // Fernhilfe (Issue #79): Der Renderer meldet seine Sicht; Main schickt erlaubte Aktionen zurück.
  helpView(view) {
    if (view && typeof view === 'object') ipcRenderer.send('pk:help-view', view);
  },
  onHelpAction(callback) {
    const listener = (_e, action) => action && typeof action === 'object' && callback(action);
    ipcRenderer.on('pk:help-action', listener);
    return () => ipcRenderer.removeListener('pk:help-action', listener);
  },
  // Abo auf Live-Events. Gibt eine Abmelde-Funktion zurück.
  onEvent(callback) {
    const listener = (_e, msg) => {
      if (msg && EVENT_TYPES.has(msg.type)) callback(msg.type, msg.payload);
    };
    ipcRenderer.on('pk:event', listener);
    return () => ipcRenderer.removeListener('pk:event', listener);
  },
});
